project:
  name: Boosty Downloader
  debug: true
  environment: development
  serviceName: bood

metrics:
#  host: 0.0.0.0
  host:
  port: 8080
  path: /metrics

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version
