// Code generated by "stringer -linecomment -type=Endpoint"; DO NOT EDIT.

package endpoint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetBlog-0]
	_ = x[GetPosts-1]
}

const _Endpoint_name = "GetBlogpost/"

var _Endpoint_index = [...]uint8{0, 7, 12}

func (i Endpoint) String() string {
	if i < 0 || i >= Endpoint(len(_Endpoint_index)-1) {
		return "Endpoint(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Endpoint_name[_Endpoint_index[i]:_Endpoint_index[i+1]]
}
